In [1]:
import numpy as np

arr = np.array([1,2,3,4])
print("Array:", arr)

matrix = np.array([[1,2],[3,4]])
print("Matrix:\n", matrix)

print("Zeros:\n", np.zeros((2,3)))

print("Arange:", np.arange(0,10,2))

a = np.array([1,2,3])
b = np.array([4,5,6])
print("Addition:", a+b)

print("Mean:", arr.mean())
print("Standard Deviation:", arr.std())

Array: [1 2 3 4]
Matrix:
 [[1 2]
 [3 4]]
Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Arange: [0 2 4 6 8]
Addition: [5 7 9]
Mean: 2.5
Standard Deviation: 1.118033988749895
